### PR TITLE
add stagehand mcp server

### PR DESCRIPTION
**Pull request by filip-michalsky**

### CODE REVIEW

**Comment by filip-michalsky** [comment]
@alexdphan

**Comment by filip-michalsky** [comment]
the demo video could be a bit better, lmk if you want me to shoot a new one, or a new scenario? @pkiv I can add extract demo too if better

**Comment by filip-michalsky** [comment]
also note on the extract:

MCP only passes strings, so I prompted the extract tool to generate a valid JSON schema, which then gets converted to zod server side - my tests worked, but there could be edge cases

**Comment by kamath** [comment]
merging into a branch so i can add to this. thanks so much filip!!

**Pull request merged**
